spring.application.name=sistema-pizzaria-java

# Banco H2 persistente
spring.datasource.url=jdbc:h2:file:./database/pizzariadb
spring.datasource.username=sa
spring.datasource.password=b@ancoP1zzar1a
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

spring.thymeleaf.cache=false
spring.jpa.defer-datasource-initialization=true